#!/bin/sh

case "$1" in
  start)
    echo "load scull and module"
    /usr/bin/scull_load
    /usr/bin/module_load faulty
    /usr/bin/aesdchar_load
    modprobe hello
    ;;
    stop)
    echo "unload scull and module"
    /usr/bin/scull_unload
    /usr/bin/module_unload faulty
    /usr/bin/aesdchar_unload
    rmmod hello
    ;;
  *)
    echo "Usage: $0 {start|stop}"
  exit 1
esac

exit 0
